//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LabSheet5
{
    using System;
    using System.Collections.Generic;
    
    public partial class Album
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public System.DateTime Released { get; set; }
        public int Sales { get; set; }
        public string AlbumImage { get; set; }
        public int BandsId { get; set; }
    
        public virtual Bands Band { get; set; }
    }
}
